name: Deployment Pipeline

on:
    push:
        branches:
            - main

           
jobs:
    deploy: 
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: "Install Ansible"
          uses: alex-oleshkevich/setup-ansible@VERSION 
          with:
            version: "9.3.0"
        - name: "Print Ansible version"
          run: ansible-playbook --version
